---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-github-webhook
  namespace: argocd
spec:
  encryptedData:
    githubWebhookSecret: AgCEzJP3uh4F7WsIB2lI66UfiILT1zcz/lJNSwnKkIDzR5UgrzMgFjIjsKfUz2VrpOvyQ/0UqqJPDV5VhwDBhRdrrsziGkdIRyeTe9VKSKwAc2/VQ3Q+UgllYdc5/dUxz1uMoqVGyAFw8ztgU1ToYv4RqnHzWdZ+FS1qQN62XLz2S+iXco4N6hvsSx4TcY9BmdftCbnYvZJXVUErmYiIBVUDgqkP+dujqaBqXnvATcCagCTQMupx0Da2W2SiOkzVoJmug2+BI1beJOyYphGx3HQG9qBBndFgMuTuO5JBI7jDfjgvzhKQY8vp1FCVBOjpCMe66jMp0tOCLe7HRi/xXUlDsH4EV4nW27R9Llf5cZnYCHJgLJ50EWNJST4ZJy76888jv56yqRVzlBHdEcRPdfVqrgN6knrNFVs+jThPgLzRz5DiPQ8Iw5vUfWGCPstmS8B/jWByHAPoYw9ZsxEJeyYLfBqPjhFQUvETy6SG8FkgG9/EuGCAeRy2dwES4scoWyRhYykN4k2S3Q0iPJC3DAmHS7Y+L71YQewrn6OanUORvStJssz1kdJqoPoS98PnwZZ7aRLLWIKSC5shtmRVyR6Zthx0o0Jlo0wFoOvgpnIDc/gheXkwZy3zGaswJK1FvCZWtRjEmTjFZZlJH7Udws53g21pseeXtu+36FlAzFiS2UTb7WG+6P2dOXcvq+tYVSwV4XvduzyPLzMZBSa2WRz69BkxcIBHluuWgG1ny1PGmXrGqioXa9AEmedaXA==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-github-webhook
      namespace: argocd
