---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-dex-github
  namespace: argocd
spec:
  encryptedData:
    clientId: AgAW0QiWYyjBZ/n4SNoNW/gRPVAv2hfL2qEFI+P/UL4VOnCc9FPByClmThfTPSj4FRa/jyxUYqrHWpKd9j2K/FhOiynQ3SmXJVAtSlBk/siJ7otp4PiutZbVvftYc5555Bo3B5jEOpyo6DFfGPL5CRSt0qovTdIokJZUbqv6dbiEN59SohbbFlJga/bgFR74PyxzOzsK7Qd0vFvxZe1PS9aTaD1FXdk4SaLNPsQbK0NUQASzjGBElktPYo58qZLy5PZJB47jVKrsBSTFR0tVGpCfnkg8SNS8q96BrA6K6SvO+2u64hbqEm2qYaJtDsdBeP2KnhzGCMQzV43OryACMPrZtq7yxScbmNT9QQEajT0sH0VOYCTt0BVq6UfrdgaGD1w8NwPhTsgrlsdUkOMxoasCfTRT07tv0YO9KVad4yWCXN/h6ZotBdCuiJzUEam0nIX+i30g35oFx8jQsKvKfWVK+vRff81k2QO3uqaLJ0gZEuQzHRM7u4Z/MxtguwXFP+qVycwovRJtIs8U9HeQoTFu2KmbQPFlJTfvyofYb/OKXg5udL3wZHqGVLuU9QxBN/ycZxrweISpq/4qCQNzfciovRhFWflCn6CmcfXkc2y1cW1qkg2L++lt0sRUXpzNTeisbaUpo4A0x8cBSSSoOdkcTP6E4gjg+oaT69kIJXCi+EKdkMvEPP27fLwJ1RMZLfAYc/I66KZ8SbvshkR7gRXHc+Cdbg==
    clientSecret: AgBwXd/IanrZsYM97zNlmFWYQ9wZD8DtOCY0pd5upp6hqTJihTHVoEqh4s4/xfEsmj2rO4QlxjrsXkUNoO8ac46mSpVELEqqeq0POM8J+mCeNe/MB5ZYX9oDxatSoqO7JSUAzXXJbevnPpDo+MQOTaRv/fbiW/E6Wm/9ieUaN2nj3yBlwQ+w2Q0hA/2gOdoepXWiXC+wu/13hqY7yjBv1zmA5UHyBtpbGmxCYKdMXx/OEAE5SVLEweek50SYyhUgzdDCSNAXpWfiHXezo1RFX40Mf1AFmxMnlwf6EhCjR/y62uEvw/vZyLvcDaj6w/jzBU7pJU1S+kdne4CMqF7BR1g0NYIGqYnCVMAaZKXpSHJe7bRAB24L/g/4aQ7eiOE7wk8Eq3ZGl3LcdSyBs19UGwjz3NXCxxehS6UVnf/VLJbVJ5Bg0mMmYyGQ3to7AsSfa6rVUjjy1fjtL0hgrQPAFc3TTDAVpKH82+76J7n1GELFmzSBm3pwBj8InJXwRUyB6gnlGy1YXdylTCk2NARrAdvnBh9TLj8NAPKj9O62XUX6BGVkdZQxzqLkJIxT9P+ro3Mtl5RHsIWispj8vJgVVQmjwSsZC/9Dv2TPZTd9DjUMr2Dl1wvQ8H7XkjbsxervoMoAUKB0l+vgR1+GlCOxyN/u/v+ChyWLPvykVhOtDmRLR0NAh6JqeObcWceq5wAYwQI0pvEenXil4XXT1acuDAGJtZWio1LZ0ugfAmiIcEi9uZkD7oTIH55P
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-dex-github
      namespace: argocd
