---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-demo-churn-credentials
  namespace: argocd
spec:
  encryptedData:
    token: AgCbVbP0YYwZM4PLMYZI4+cDQAVrAidpDhvaVNWrzv2cGGuDO15bGOZjX5cXs0twdpwp5OaNvh3Jk4MGvA5HE8fFm1i0UniIqdqXki6H5IxIMlhbNt6jkiJfobVEqqmbZnB16vp/LSEAEFkqNzLUje/Oe4Vzl4wRKJX4RGXVaVIpRQtSLcQM687rCW6c5GDp9OtjJZXWcyz0e6c4O23wojdiJLH/3W/HKloE0zmpJ7LQOt79JM8imfQTH2LIXLJ4dX/VfJqBUCtibhXn1BGJCekzKRqAFnKs2iMwcZwD3Pmv4azi4Czug9VvECJMTg+8jfhjBQHXbsqvM20xHs8hs0tQhaioB9M4sh2vVbBsM4CMvVyKkJW2j5DYpeu6AfPF/8+PfRMUFz5nxA4A+gJPNcFZOSJB2m1baDmlXWrhwV+izViuWU6WJC+cq6cijmtqMlgcQGveBgXdu5PrqkJal+U6EGowcpi1Jte7BuYKUbD1S977VWmI6jSDL8TnpskhCNGlqb4291T+6Ko6FxRpoYU5UV7ZsIR8jKBzGEnXJ/99sC5l119IHmpknhShyjBKuwsoBzjvJRdYKonry3hngHSziVoCol25CZsOezYa2l1RhHkPTjI3gtVATyJLRlRcKiMkAUdIUaR3tREAv4X2zCwfWmP0D4shou2U2v9tRxSCxhsby5zZW8QMb4/VPvcCH1U+/4Ho7/J68BkWQyhFkCpu9lDxKfo7xYcJl1oXqFwv4mtt9xePwd4jgA4Wsdzn63BpwbXgG+7y0uHbZOX1ug==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: gitlab-demo-churn-credentials
      namespace: argocd
