---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-demo-churn-credentials
  namespace: argocd
spec:
  encryptedData:
    token: AgCb6iQduPy9cjWbPAMziI+xnw/jJ4dwX2Eqbyhqa3P3BRwZX1YQwRTdcdt536n1omNZR0uZXedZuauEz+PaQ0oVfUYkapocKPfLFTtw+UMdho6okqFhOTYXqQEjHKdMjpougzTdWLGLHIuoJBGtWLUO3HSyHrV5X1aZK5SGpDd3AYA5r43p7g8S+ORm5NesChFIUif3EQLpqy6pAGSVfu6XXLJgyK5l4UnOE/FA4QW9yDDqZPEdb6wYs3heMDHgaN9PIHmUqxgkblxJzTvR2v8zl6/7uRZ8rl1EwoYZLsq5C7EOj7D+bvr9mmhVYMJpT+VHZYC2odQvqlprASIXxzlKJuS+F8c7a9EeStNVU3w4UyfR4C7kg7RXSJ+wYCVXJ7+BtWkyzQK1n5FWjy7F9pPUebZiPMi3Txiu0RDbDbAuGEAZ6Q7INOtK/yj3W7an65F4kHEofgPwdqTWlMvpAqz/g1dUWeFAZxvfbkCZJNGGGhADHqDUe3mzLZDNao3AM1vhHlJOse3aRpHOGMLnRXawMclHG95/yzPwppm/D+FFOS4fjCIHLmF9G7rUtOLtIHCg14WZ32ZWAk2Ujfj6NtC9l+5diJwPIANhYdb6pbEhjeJz49iBKUdwZ8WJcTf+SDOTpEsxn7FTsJEsblJcKOYtH5R8yCEgnvqd8OKqygsdHDj6Yni8mdrEenXW/0LUQGutK6ExuMxqkeyw920ysyvh8yp5j1KHEcJly0p55dOS5rIMjvT3HIwnQ1uCGuVy+HhgaGkV5eJgwSSn+rXy9g==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: gitlab-demo-churn-credentials
      namespace: argocd
