---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-scm-credentials
  namespace: gitops-promoter
spec:
  encryptedData:
    token: AgDCkMiIaYN5AKC3/WJbZ2utCAw4xoxD20eUxiNtOzE7dEoqx8+F/Drl3XZzUe8oMFmwxjDgl7IKaH0SsQxHsbMHjSgI2EvssGYG06Sm6rwNmC4pwi78DpjvmR0U41DkS/z7pr1tCU7LANtA8l/zzlxacetmlQRXQFQPUXSAlhnHEHrgvRGL7uJW6gIkyuEWY/pikotwaHU+Tfsm0OkePNWOKcDoM5BHWetC/Vwxa/iRE9czVbLP5RFOCTFwgSwLsIQBQX4fi7LkO0fPknie812Ps8gog2OOklKLDgMK7GFVmjalqAtb9fTReHGqAjtEPw3ndKnXqgDHrBvayEm0+oTFoYrmPaxoYJmcvWkxFKcVQ4foWF6wsiotQZKXLDqpWTnqCsf14lBy0m92yzjyez/1Ck5Rhfc+icVD3kN8IzbIC9lafUhHjf67ryk7XeOXcZXowP26alwZJFrH38BjNvECGn4Fj8prATucq0EujtCETnz2U8uGLTTXZW1uo4SNNDsRo3iLb/G0x/V2q0UfacQ6OmMvkrGUZ2Td7F0Su8GdFxzPyalSqFx3L1tmPpcn6gtHOr8O3I8/utUfXsytn/dQMMcI9CSsI43utDrLZxIzQkKiw3wKPdfKTz2/vhgw8/3XvGrEu8n/nMgvfzXYr9UoXoXTLJzkJOEkEWaW8IZC138u7cGGNLTRPmTbizXSXTAzJ6VZfKwNWwQeoWCG/Dn3m3J9m+WcmBs26jGLs6JPtn8SU6dR2wKS4EX6tvvCXvuhXJaqUOU+EdTTq6Er1Q==
  template:
    metadata:
      name: gitlab-scm-credentials
      namespace: gitops-promoter
