---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-scm-credentials
  namespace: gitops-promoter
spec:
  encryptedData:
    token: AgAH+F6RMb91DzZm1RFUNRIKzHZ5djzk6NnxUgNRWyZPl2GqAD/R7oHFqDk7wl3hgGw9jVI3RXqndk3bzyZs0/1P/0qwtkhE5zeguBxOfCHtQU/bZV+ynJy50p5CL2I6Bk3HKThXluE1rSXeFkNlUIn/V8cN5vz+J24j5vdmPMmMeQ7TTNM/JRrf/Oyy8pP+NvTilFyUpC9DQJlA5O5VGr4XlCxCsP6oYrrw6p0xuVvCl7MfB2dzcgkFq2aKykyQ2wtaj/BrwLS8l60SEHqNAcam/1y/2VOwTRRVPckLSH00XPC461c9MQQuxBSL1RQnH4vze8C2FU2t9YRGNjrJViwBSDZWEGmskHWBP97V6DJ8TdOPIOuGKdfREaKZg41HwndzyjHzZdkwQE386irIE2LUVRWOrYEd0HmYLTpm1BwDlRBam8iLxwmBAD+CCngmWnfRtyjcL1ju666DFH0W0e0WX3WxInCy2i9hFwduprvsdrH52WrH+VWAZdOdMKT43jN7/LEEWRrjZJ2MC303nTTA4K9Kf+J0cbYw9LXIpT9eY4zg/J9Ql3D3TZSDMUF3PSbrkUeqQfVTgf2sP2Rf8S8lur21tyE8QeHcgZUVn8hb0VECcObxZPVK8QqiM8NWgcnBvED/QY/ybUraUaedo1SzTZR4EXj7WbYzpwcaZ+7kW2r15fF57ZaArhhHdOLZwFdAfeXvs8wcpCfCoh49AwUBcyT48BZ/HTgpfkXc85KFqCIZS18OLXxmwTFNF7hpvsE7LKZvlosEl4qr1CC27g==
  template:
    metadata:
      name: gitlab-scm-credentials
      namespace: gitops-promoter
