apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  name: demo-gitlab
  namespace: gitops-promoter
spec:
  gitRepositoryRef:
    name: demo-config-gitlab
  activeCommitStatuses:
    - key: argocd-health
    - key: timer
  environments:
    - branch: env/dev
      autoMerge: true
    - branch: env/e2e
      autoMerge: true
    - branch: env/prd
      autoMerge: true
