apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-gitlab-prd
  namespace: argocd
  labels:
    app.kubernetes.io/name: guestbook
    guestbook-env: prd
    demos.gitops-promoter.dev/instance: gitlab
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    promoter.argoproj.io/has-promotionstrategy: "true"
spec:
  project: default
  sourceHydrator:
    drySource:
      repoURL: {{ .Values.guestbookGitLabRepoURL | quote }}
      targetRevision: HEAD
      path: demo-apps/guestbook
      helm:
        releaseName: guestbook-gitlab-prd
        valueFiles:
          - env/prd/values.yaml
    syncSource:
      targetBranch: env/prd
      path: hydrated/guestbook-gitlab-prd
    hydrateTo:
      targetBranch: env/prd-next
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-gitlab-prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
