apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promoter-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  sources:
    - repoURL: {{ .Values.repoURL | quote }}
      targetRevision: HEAD
      path: promoter-config-github
      directory:
        recurse: true
    - repoURL: {{ .Values.repoURL | quote }}
      targetRevision: HEAD
      path: promoter-config-gitlab
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-promoter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
