---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-github-oauth
  namespace: monitoring
spec:
  encryptedData:
    clientId: AgBCCzqWJLzgacsOGJgRtKF4HS05MSkI7Zxcdukidp/zEzZ+PsP+8smKl7cqmXkEFf9D9VG/M7J+EbGwLQaKEakvDrzdTgXZbGbKJQPEJ9tu8dKmn7zKsoCV98WCH386uHXBe1tuBFk4vnqdgsYYJ2FXcsYx0pKv5xNjBu6qBZZza0VlhTAY2GBwd6UIkSSUDLrWAsLSJALk8NJY6f2Bw63pJLPbCR2GYIhNX0IIaBvQ/AXUaRa9SBf5GDlNnSKnqZY5CJS18elMOvuUkz+baMVd1+2WmJ39GqbayxSjfkzt3zDgEHjusDrIx53tpq7XRUPNyfpw18ot2Hw6lZrMY/zywZWZknaCOMGoAc2Q1ckj4TOg+WqkGcSUlWSpcGgdnfynSycCIofi+n3ZWNuGw1J3LIF+2HrOF+RC+QXZNoLTwsZ/v6M3pquI+Emqcy8sIQh00aox2jcDi6eflq45B06ryusmQI94Y2sIwPgcx0YX3Zf1RVpmzTEd9tU6MZWgKV8AvDY1O++1aFLVl5XFJsIxJN7mEpzti383zNBxO131Q6rLx0AxLlaKtK97vA0yIkJqid/vmyxjdnshdzvzCWyCSFstGFW9MLz7I265re8AP+2r6oK9toItkvCTt7oOFc1vUM+b9+CRmLKzzW9R2imiywjSFDaV96aq8vyjFr8HprHk4ZcVdlChrXZ4MrD/H/Hb+dyL3swBkNcwFXJWCmntVW6GeQ==
    clientSecret: AgCTUIfj4MBdb4JbwX9BPuzW3TS+7ioLLL5kvCiMu298Zlukvvsnl7uE57wWDV9EaCmsvk6FPRQtWJ8dApCzL5Fdntf0xY1IUp6y2Vhhq193MrpwNvXbRReSq6WTYhlFiJv97hpeDTBGyXyggplACwtRG5lCw8l9YX13uPQpm1Qx15ewgZSrQI7Ca5m6d25YjvCIgsbBC4hmHrVFF49yR/gtpfD6wWGWwl89A/Boztot//BFV9wCOgT+o3cPyxZhMa1eAKQjCTV3/CV6yDKdDeNnvGB+G26XQ9+fZDkjqRNzMSHZno++QCPF+eIKiuLEjX+ZRrJz/c5NnrBtal/P6KW0Gur8ez0r+mZq8cu+LlZRmm7A0k2QPaKWdrlQZ4Fd9p6cf8KWAJ/853YlaaAyxW/K7EYADAEBFgcM5L+m6eRgFUDWz0fyRJzcXun4I/6i7+tdUDQqEwcYkxRkgam/pWWuH9zrsSlMOd2gKUVE1J/iIBN0WN1XKc8NwNGmywBvyyfSaAYULaQRNstPbAJVWwxgSv258pjNcoB4XGfZSbmIhvP6bPG7AkK3W2/FGq0rqvGwMfppYCTDYGlAESY8OXvUuDjPjfjqwxfW/Rsr9sc8auU9Y/Bfdo/j5Tt+Pw0o6evmz7Y84w5De4FwjNcYby0y3XBtVcS0EUvJTen07n1yPmSE4B7+pnIcJrFnqMYnNX1vDXPvX0g9q+W750q3C4D95qywv90H8rkfsITzRrT632LvLnO3Q5rf
  template:
    metadata:
      name: grafana-github-oauth
      namespace: monitoring
